// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbeoscmqbmzfoqyutmgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiZW9zY21xYm16Zm9xeXV0bWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MjM0NjUsImV4cCI6MjA2ODE5OTQ2NX0.Yp1F-Gg8ZCCv8lb_fLodHiU9KwIyTSHT48NQqmODjdg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});